package com.myeasydb.demo.model;

import com.j256.ormlite.field.DatabaseField;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class SimpleData {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	public int id;
	@DatabaseField(index = true)
	public String string;
	@DatabaseField
	public long millis;
	@DatabaseField
	public Date date;
	@DatabaseField
	public boolean even;
	@DatabaseField
	public String ext;
	@DatabaseField
	public String ext1;

	public SimpleData() {
		// needed by ormlite
	}

	public SimpleData(boolean even) {
		this.even = even;
	}

	public SimpleData(long millis) {
		this.date = new Date(millis);
		this.string = (millis % 1000) + "ms";
		this.millis = millis;
		this.even = ((millis % 2) == 0);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("string=").append(string);
		sb.append(", ").append("millis=").append(millis);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=").append(dateFormatter.format(date));
		sb.append(", ").append("even=").append(even);
		sb.append(", ").append("ext=").append(ext);
		sb.append(", ").append("ext1=").append(ext1);
		return sb.toString();
	}
}
